# Generated by Django 4.1.1 on 2022-09-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
