# Generated by Django 4.1.1 on 2022-09-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userprofile_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('answers', models.ManyToManyField(to='User.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(to='User.question')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quizzes',
            field=models.ManyToManyField(to='User.quiz'),
        ),
    ]
