# Generated by Django 4.1.1 on 2022-09-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_answer_question_quiz_userprofile_quizzes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
