# Generated by Django 4.1.1 on 2022-09-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_answer_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
