# Generated by Django 4.1.1 on 2022-09-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
